platform :ios,’9.0’
target 'MobileOA' do
#pod 'AFNetworking’,’~>2.6.0’
pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
pod 'SDWebImage', '~> 3.7.3'
#pod 'IQKeyboardManager', '~> 3.3.0'
pod 'IQKeyboardManager'
pod 'MBProgressHUD', '~> 0.9.1' 
pod 'MJRefresh', '~> 3.0.1'
pod 'Reachability', '~> 3.2'
pod 'MJPhotoBrowser', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.10'
#pod 'BlocksKit', '~> 2.2.5'
pod 'BlocksKit', git: 'https://github.com/LDXu/BlocksKit.git', branch: 'v2.5'
pod 'YUChineseSorting', '~> 1.0.2'
pod 'HPGrowingTextView', '~> 1.1'
pod 'YYKit', '~> 1.0.9'
pod 'MyLayout' 
end




#import "AFNetworking.h"
